// MetaDataApiSample01.idl : MetaDataApiSample01 の IDL ソース
//

// このファイルは、タイプ ライブラリ (MetaDataApiSample01.tlb) およびマーシャリング コードを
// 作成するために MIDL ツールによって処理されます。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(CB372775-EF3B-4D44-B033-CC6638C3AB55),
	dual,
	nonextensible,
	helpstring("IAppDomainGen インターフェイス"),
	pointer_default(unique)
]
interface IAppDomainGen : IDispatch{
};
[
	object,
	uuid(940B2252-DB28-414D-A615-49F7E7B1EFD0),
	dual,
	nonextensible,
	helpstring("IAssemblyGen インターフェイス"),
	pointer_default(unique)
]
interface IAssemblyGen : IDispatch{
};
[
	object,
	uuid(8DC18C9B-60C7-415C-AD30-2B09E56654DB),
	dual,
	nonextensible,
	helpstring("IAssemblyGenCollection インターフェイス"),
	pointer_default(unique)
]
interface IAssemblyGenCollection : IDispatch{
};
[
	uuid(300EAE93-937E-4B29-A02A-29FB75328EC4),
	version(1.0),
	helpstring("MetaDataApiSample01 1.0 タイプ ライブラリ")
]
library MetaDataApiSample01Lib
{
	importlib("stdole2.tlb");
	[
		uuid(965DB760-A27B-4592-8A32-23F4E22EB167),
		helpstring("AppDomainGen Class")
	]
	coclass AppDomainGen
	{
		[default] interface IAppDomainGen;
	};
	[
		uuid(6D2E93D6-6364-4FA7-90CF-E7861E875D9F),
		helpstring("AssemblyGen Class")
	]
	coclass AssemblyGen
	{
		[default] interface IAssemblyGen;
	};
	[
		uuid(FA217239-6436-4D05-80AA-CFAB4A86A16F),
		helpstring("AssemblyGenCollection Class")
	]
	coclass AssemblyGenCollection
	{
		[default] interface IAssemblyGenCollection;
	};
};
