// Sample02.idl : Sample02 の IDL ソース
//

// このファイルは、タイプ ライブラリ (Sample02.tlb) およびマーシャリング コードを
// 作成するために MIDL ツールによって処理されます。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(324FA781-2E07-415E-B60B-93D2A535DD90),
	dual,
	nonextensible,
	helpstring("IMyCache インターフェイス"),
	pointer_default(unique)
]
interface IMyCache : IDispatch{
    [propget, id(2), helpstring("プロパティ Count")] HRESULT Count([out, retval] LONG* pVal);
    [propget, id(3), helpstring("プロパティ Item")] HRESULT Item([in] BSTR key, [out, retval] VARIANT* pVal);
    [propput, id(3), helpstring("プロパティ Item")] HRESULT Item([in] BSTR key, [in] VARIANT newVal);
    [propget, id(DISPID_NEWENUM), helpstring("プロパティ _NewEnum"), restricted] HRESULT _NewEnum([out, retval] IUnknown** ppVal);
};
[
	object,
	uuid(4C29DB1F-A3FA-47C9-9874-B7FF64864EF6),
	dual,
	nonextensible,
	helpstring("IPairStrVariant インターフェイス"),
	pointer_default(unique)
]
interface IPairStrVariant : IDispatch{
    [propget, id(1), helpstring("プロパティ First")] HRESULT First([out, retval] BSTR* pVal);
    [propput, id(1), helpstring("プロパティ First")] HRESULT First([in] BSTR newVal);
    [propget, id(2), helpstring("プロパティ Second")] HRESULT Second([out, retval] VARIANT* pVal);
    [propput, id(2), helpstring("プロパティ Second")] HRESULT Second([in] VARIANT newVal);
};
[
	object,
	uuid(F794302C-AD7E-4DA9-A000-794FDC32AF49),
	dual,
	nonextensible,
	helpstring("IMyCachePrinter インターフェイス"),
	pointer_default(unique)
]
interface IMyCachePrinter : IDispatch{
    [id(1), helpstring("メソッド Print")] HRESULT Print(void);
};
[
	uuid(66E14A4E-F4D6-4EE3-A6CB-ECB383F236A0),
	version(1.0),
	helpstring("Sample02 1.0 タイプ ライブラリ")
]
library Sample02Lib
{
	importlib("stdole2.tlb");
	[
		uuid(206584CE-D105-4FB6-9B13-E6FA6CE227B9),
		helpstring("MyCache Class")
	]
	coclass MyCache
	{
		[default] interface IMyCache;
	};
	[
		uuid(37C6DACC-3125-4568-B6C5-0EED9373C7C2),
		helpstring("PairStrVariant Class")
	]
	coclass PairStrVariant
	{
		[default] interface IPairStrVariant;
	};
	[
		uuid(E8A92313-2962-4844-8086-5120A29AD7FF),
		helpstring("MyCachePrinter Class")
	]
	coclass MyCachePrinter
	{
		[default] interface IMyCachePrinter;
	};
};
